apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s-metaname
spec:
  selector:
    matchLabels:
      app: nestjs-k8s-matchlabel
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k8s-matchlabel
    spec:
      containers:
        - name: nestjs-k8s-container
          image: khanhvuvn/nestjs-k8s:v1.0.0
          ports:
            - containerPort: 3000